# Generated by Django 4.2.1 on 2023-05-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_artist_options_alter_artist_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
